### ISSUE TITLE
change vehicle spawn point heading

### ISSUE THREAD

**Issue by JustMeGaming** [KlibrDM/esx_carthief#14]
Using the original config files from first upload, I can't seem to change the heading of when the car is spawned. I changed the location to start the job at the door, and moved the spawn car location inside the garage.

**Comment by KlibrDM** [comment]
Added car spawn orientation in latest commit. You will find what you need in config.lua at line 20, or if you already have a modified version of the script and don't want to update for such a small thing, you can change the vehicle orientation in client/main.lua, on line 80 by changing the 5th parameter (0,0) to whatever you wish (from what I understand you would need 270.0)
