### ISSUE TITLE
timer

### ISSUE THREAD

**Issue by XxFri3ndlyxX** [KlibrDM/esx_carthief#5]
So i have been trying to add a timer so that they cant do this over and over. The code somewhat works. 
```
-- Key Controls
Citizen.CreateThread(function()
	local timer = false
  while true do
    Citizen.Wait(0)
    if CurrentAction ~= nil then
      SetTextComponentFormat('STRING')
      AddTextComponentString(CurrentActionMsg)
      DisplayHelpTextFromStringLabel(0, 0, 1, -1)
      if IsControlJustReleased(0, 38) then
				if CurrentAction == 'carthief_menu' and not timer then
						Countdown = GetGameTimer() + 100 * 1000
            timer = true
					SpawnCar()
					end
				end
				if IsControlJustReleased(0, 38) then
				  if CurrentAction == 'cardelivered_menu' and timer ~= false then
          FinishDelivery()
				end
			end
			elseif timer then
				local secsRemaining = math.ceil((Countdown - GetGameTimer()) / 1000)
				secsRemaining = secsRemaining - 1
				if secsRemaining > 0 then
						drawText('Please wait ~r~'..secsRemaining..'~w~ until you can get a new Vehicle',0,1,0.5,0.001,0.3,255,255,255,255)
				else
						timer = false
						print(timer)
				end
        CurrentAction = nil

    end
  end
end)
```
```
function drawText(text,font,centre,x,y,scale,r,g,b,a)
	SetTextFont(font)
SetTextProportional(0)
SetTextScale(scale, scale)
SetTextColour(r, g, b, a)
SetTextDropShadow(0, 0, 0, 0,255)
SetTextEdge(1, 0, 0, 0, 255)
SetTextDropShadow()
SetTextOutline()
SetTextCentre(centre)
SetTextEntry("STRING")
AddTextComponentString(text)
	DrawText(x , y)
end
```
The problem is that i can't figure how to draw text only if in marker. 
Could you please assist me thanks ! Really love this script :)

**Comment by KlibrDM** [comment]
I'm gonna be honest the code you have there is a bit of a mess and drawText should not even be in the key controls. Check out cd290ce8ecdfa76ff084e51924405a14a58cad36 (latest commit). I added a server sided cooldown so people can't steal one car after another.

**Comment by XxFri3ndlyxX** [comment]
Thank you for being honest. I am very new to lua but at least i am trying. It is challenging for me to make codes and stuff but one thing for sure is that i will look at the latest commit and see how it should be done. I'm really trying to learn.  Thanks!

**Comment by KlibrDM** [comment]
I'm sorry if I sounded somewhat rude. What you had there wasn't terrible, just messy. You will get better at keeping the code clean and straight-forward, just keep practicing.

**Comment by XxFri3ndlyxX** [comment]
Hey just to let you know. I took this as a good criticism so do not worry about me thinking you were rude. Because i wasn't. I only wanted to state that i'm trying unlike others who don't even bother to try and also because you showed me the correct way. I learned something new today. Thanks for the reply :)
